package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.buildSteps.qodana
import jetbrains.buildServer.configs.kotlin.ideaInspections
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        gradle {
            tasks = "clean build"
            jdkHome = "%env.JDK_17_0_x64%"
        }
    }
    steps {
        insert(1) {
            qodana {
                linter = jvm {
                }
            }
        }
        insert(2) {
            ideaInspections {
                pathToProject = "build.gradle.kts"
                jvmArgs = "-Xmx1024m -XX:ReservedCodeCacheSize=512m"
                targetJdkHome = "%env.JDK_17_0_x64%"
                ideaAppHome = "%teamcity.tool.intellij.ideaIU-2023.1.2%"
            }
        }
    }
}
